"""Published and regression test vectors.

* RFC 4226 Appendix D  - HOTP, SHA-1, 6 digits, counters 0..9
* RFC 6238 Appendix B  - TOTP, SHA-1/256/512, 8 digits, 30 s period

These are independent of this code base, so passing them shows the
implementation is interoperable with other standard OTP software.
"""

from __future__ import annotations

import base64
from typing import Any, Dict, List

from .core import OTPConfig, TOTP


def b32(raw: bytes) -> str:
    return base64.b32encode(raw).decode("ascii").rstrip("=")


# RFC 4226 Appendix D: secret is ASCII "12345678901234567890"
RFC4226_SECRET = b"12345678901234567890"
RFC4226_EXPECTED = [
    "755224", "287082", "359152", "969429", "338314",
    "254676", "287922", "162583", "399871", "520489",
]

# RFC 6238 Appendix B: the seed differs per hash (length = hash output size)
RFC6238_SECRETS = {
    "sha1": (b"1234567890" * 2)[:20],
    "sha256": (b"1234567890" * 4)[:32],
    "sha512": (b"1234567890" * 7)[:64],
}
RFC6238_TIMES = [59, 1111111109, 1111111111, 1234567890, 2000000000, 20000000000]
RFC6238_EXPECTED = {
    "sha1": ["94287082", "07081804", "14050471", "89005924", "69279037", "65353130"],
    "sha256": ["46119246", "68084774", "67062674", "91819424", "90698825", "77737706"],
    "sha512": ["90693936", "25091201", "99943326", "93441116", "38618901", "47863826"],
}

# Fixed secret for the project's default configuration (SHA-256, 6 digits).
PROJECT_SECRET = b32(RFC6238_SECRETS["sha256"])
PROJECT_TIMES = [0, 29, 30, 59, 60, 1700000000, 1700000029, 1700000030]


def rfc6238_vectors() -> List[Dict[str, Any]]:
    vectors = []
    for algorithm, expected_list in RFC6238_EXPECTED.items():
        for timestamp, expected in zip(RFC6238_TIMES, expected_list):
            vectors.append(
                {
                    "source": "RFC 6238 Appendix B",
                    "algorithm": algorithm,
                    "digits": 8,
                    "period": 30,
                    "secret_base32": b32(RFC6238_SECRETS[algorithm]),
                    "timestamp": timestamp,
                    "expected_otp": expected,
                }
            )
    return vectors


def rfc4226_vectors() -> List[Dict[str, Any]]:
    return [
        {
            "source": "RFC 4226 Appendix D",
            "algorithm": "sha1",
            "digits": 6,
            "secret_base32": b32(RFC4226_SECRET),
            "counter": counter,
            "expected_otp": expected,
        }
        for counter, expected in enumerate(RFC4226_EXPECTED)
    ]


def project_vectors() -> List[Dict[str, Any]]:
    """Regression vectors for the default config (generated by this code)."""
    config = OTPConfig()
    totp = TOTP(config)
    return [
        {
            "source": "project regression (default config)",
            "algorithm": config.algorithm,
            "digits": config.digits,
            "period": config.period,
            "secret_base32": PROJECT_SECRET,
            "timestamp": timestamp,
            "counter": totp.counter_at(timestamp),
            "expected_otp": totp.code_at(PROJECT_SECRET, timestamp),
        }
        for timestamp in PROJECT_TIMES
    ]


def export_vectors() -> Dict[str, Any]:
    return {
        "note": "Demo secrets only. Never reuse them in a real system.",
        "rfc4226_hotp": rfc4226_vectors(),
        "rfc6238_totp": rfc6238_vectors(),
        "project_regression": project_vectors(),
    }